# This builds the repo and then uploads an artifact to a S3 bucket
# Then it will deploy the newly uploaded version to the public S3 bucket

name: Frontend DEV

env:
  S3_ARTIFACT_BUCKET: ${{ github.repository_owner }}-${{ github.event.repository.name }}-dist
  S3_DEV_BUCKET: ${{ github.repository_owner }}-${{ github.event.repository.name }}-dev
  AWS_DEFAULT_REGION: "eu-west-1"
  NODE_VERSION: 12.4.0

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
    paths-ignore:
      # We don't need to do builds on README changes.
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      artifact: ${{ steps.upload.outputs.artifact }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Set archive version
        run: echo "ARCHIVE=build-${GITHUB_REF#refs/heads/}.${GITHUB_RUN_NUMBER}.tgz" >> $GITHUB_ENV
      - name: Set archive tag version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "ARCHIVE=release-${GITHUB_REF#refs/tags/}.tgz" >> $GITHUB_ENV
      - name: Upload to AWS S3 Bucket - ${{ env.S3_ARTIFACT_BUCKET }}
        id: upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        # The name of the archive must include the build number to allow us to cleanup older versions
        run: |
          echo "$ARCHIVE"
          tar -C __build__ -zcvf $ARCHIVE .
          aws s3 cp $ARCHIVE s3://${S3_ARTIFACT_BUCKET}/
          echo "::set-output name=artifact::$ARCHIVE"

  deploy-dev:
    runs-on: ubuntu-20.04
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      ARCHIVE: ${{ needs.build.outputs.artifact }}
    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: dev
      - name: Download ${{ env.ARCHIVE }} build from S3
        run: aws s3 cp s3://${S3_ARTIFACT_BUCKET}/${ARCHIVE} build.tgz
      - run: mkdir files
      - name: Unzip files
        run: tar -zxvf build.tgz -C files
      - name: Upload to bucket ${{ env.S3_DEV_BUCKET }}
      # This is so that if the upload was done after a newer build was completed we still upload all the files.
        run: aws s3 cp files "s3://${S3_DEV_BUCKET}/" --recursive --no-progress
      - name: Remove old files
      # This removes the old files.
        run: aws s3 sync files "s3://${S3_DEV_BUCKET}/" --delete --no-progress
      - name: Update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  cleanup-artifacts:
    runs-on: ubuntu-20.04
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Delete old versions from S3 bucket
        run: aws s3 ls s3://${S3_ARTIFACT_BUCKET}/ | sort -rn | awk -v s3_url="s3://${S3_ARTIFACT_BUCKET}/" '$4 ~ /build/ {print s3_url $4;}' | tee /dev/stderr | tail -n +21 | xargs -r -n 1 aws s3 rm